# Setup
title:        Sandeep
tagline:      Engineer | Builder
baseurl:      ""
paginate:     1
locale:       "en"
copyright:    2023 Sandeep

# About/contact
author:
  name:       Sandeep
  url:        https://ethereal-sandeep.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
