# Setup
title:        Zero
tagline:      Engineer | Builder
baseurl:      ""
paginate:     1
locale:       "en"
copyright:    2023 Zero

# About/contact
author:
  name:       Zero
  url:        https://ethereal-sandeep.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
